### ISSUE TITLE
Json/XML SQL Functions

### ISSUE THREAD

**Issue by rsdpyenugula** [BlazingDB/pyBlazing#109]
**Flatting Json **
In the document it says it supports all the JSON function via cuIO not sure can it be performed in the SQL or not.

**Describe the solution you'd like**
Reading the  JSON document using SQL functions and flatting it to a  table and other functions that will help for data validation similarly  do it for XML document

**Ref**
https://docs.snowflake.net/manuals/sql-reference/functions-semistructured.html
https://spark.apache.org/docs/latest/api/sql/index.html  (XML and Json  Fucntions)

**Comment by felipeblazing** [comment]
Yes you create a table from it like you would any other file

**Comment by rsdpyenugula** [comment]
@felipeblazing , I  mean creating the table with  JSON file and  Flatting the JSON in the SQL?  is it possible and is it the same with XML?
