### ISSUE TITLE
[BUG] - AttributeError: 'BlazingContext' object has no attribute 'need_shutdown'

### ISSUE THREAD

**Issue by SinsBre** [BlazingDB/pyBlazing#117]
**Describe the bug**
After 25.10.19 I have not been able to get Blazingsql to work.

**CODE:**

python3.7

from blazingsql import BlazingContext

bc = BlazingContext()
...
**Output:**
WARNING: blazingsql-orchestrator was not automativally started, its probably already running
WARNING: blazingsql-engine was not automativally started, its probably already running
^CTraceback (most recent call last):
  File "cs_dataprep.py", line 17, in <module>
    bc = BlazingContext()
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 173, in __init__
    internal_api.SetupOrchestratorConnection(orchestrator_host_ip, orchestrator_port)
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/pyblazing/api.py", line 904, in SetupOrchestratorConnection
    client.connect(orchestrator_host_ip, orchestrator_port)
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/pyblazing/api.py", line 353, in connect
    self._orchestrator_port, requestBuffer)
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/pyblazing/api.py", line 311, in _send_request
    return client.send(requestBuffer, expect_response)
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/blazingdb/protocol/__init__.py", line 69, in send
    length = struct.unpack('I', self.connection_.socket_.recv(4))[0]
KeyboardInterrupt
Exception ignored in: <function BlazingContext.__del__ at 0x7fccc269bbf8>
Traceback (most recent call last):
  File "/home/REMOVED/miniconda3/envs/blazing2/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 212, in __del__
    if self.need_shutdown:
**AttributeError: 'BlazingContext' object has no attribute 'need_shutdown'**

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux REMOVED-ub 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Oct 28 10:13:09 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce RTX 2080    Off  | 00000000:01:00.0  On |                  N/A |
     | 24%   30C    P8    12W / 215W |    692MiB /  7979MiB |     10%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      1192      G   /usr/lib/xorg/Xorg                            28MiB |
     |    0      1227      G   /usr/bin/gnome-shell                          57MiB |
     |    0      1497      G   /usr/lib/xorg/Xorg                           195MiB |
     |    0      1630      G   /usr/bin/gnome-shell                         147MiB |
     |    0      2642      G   /snap/pycharm-community/155/jbr/bin/java       8MiB |
     |    0     15504      C   blazingsql-engine                            249MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              8
     On-line CPU(s) list: 0-7
     Thread(s) per core:  1
     Core(s) per socket:  8
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               158
     Model name:          Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
     Stepping:            12
     CPU MHz:             4615.365
     CPU max MHz:         4900,0000
     CPU min MHz:         800,0000
     BogoMIPS:            7200.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            12288K
     NUMA node0 CPU(s):   0-7
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
     
     ***CMake***
     /home/REMOVED/miniconda3/envs/blazing2/bin/cmake
     cmake version 3.15.4
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/REMOVED/miniconda3/envs/blazing2/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/REMOVED/miniconda3/envs/blazing2/bin:/home/REMOVED/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/REMOVED/.local/bin:/home/REMOVED/.local/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/REMOVED/miniconda3/envs/blazing2
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/REMOVED/miniconda3/condabin/conda
     # packages in environment at /home/REMOVED/miniconda3/envs/blazing2:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     alsa-lib                  1.1.5             h516909a_1001    conda-forge
     arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
     blazingsql-calcite        0.4.5                         0    blazingsql
     blazingsql-communication  0.4.5                cuda10.0_0    blazingsql/label/cuda10.0
     blazingsql-io             0.4.4                         0    blazingsql
     blazingsql-orchestrator   0.4.5                         0    blazingsql
     blazingsql-protocol       0.4.5                    py37_0    blazingsql
     blazingsql-python         0.4.5           cuda10.0_py37_0    blazingsql/label/cuda10.0
     blazingsql-ral            0.4.5                cuda10.0_0    blazingsql/label/cuda10.0
     blazingsql-toolchain      0.4.5                         0    blazingsql
     bokeh                     1.3.4                    py37_0    conda-forge
     boost                     1.70.0           py37h9de70de_1    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_1    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.9.11            hecc5488_0    conda-forge
     certifi                   2019.9.11                py37_0    conda-forge
     chardet                   3.0.4                    pypi_0    pypi
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_0    conda-forge
     cmake                     3.15.4               hf94ab9c_0    conda-forge
     cppzmq                    4.4.1                hc9558a2_0    conda-forge
     cudatoolkit               10.0.130                      0
     cudf                      0.10.0                   py37_0    rapidsai
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.6.0                      py_0    conda-forge
     dask-core                 2.6.0                      py_0    conda-forge
     dask-cudf                 0.10.0                   py37_0    rapidsai
     distributed               2.6.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.5           py37h516909a_0    conda-forge
     flatbuffers               1.11                     pypi_0    pypi
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.5.2                      py_0    conda-forge
     geoip2                    2.9.0                    pypi_0    pypi
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmock                     1.10.0                        0    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     gtest                     1.10.0               hc9558a2_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                      pypi_0    pypi
     jinja2                    2.10.3                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     lcms2                     2.9                  h2e4bb80_0    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.10.0               cuda10.0_0    rapidsai
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     libgpg-error              1.36                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0             h19a2143_1004    conda-forge
     libhdfs3                  2.3               h311b756_1006    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libntlm                   1.4               h14c3975_1002    conda-forge
     libnvstrings              0.10.0               cuda10.0_0    rapidsai
     libopenblas               0.3.7                h6e990d7_2    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.10.0               cuda10.0_0    rapidsai
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.33.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.9                hee79883_5    conda-forge
     llvmlite                  0.30.0           py37h8b12597_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     maven                     3.6.0                         0    conda-forge
     maxminddb                 1.5.1                    pypi_0    pypi
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     ncurses                   6.1                  he6710b0_1
     numba                     0.46.0           py37hb3f55d8_0    conda-forge
     numpy                     1.17.3           py37h95a1406_0    conda-forge
     nvstrings                 0.10.0                   py37_0    rapidsai
     olefile                   0.46                       py_0    conda-forge
     openjdk                   11.0.1            h46a85a0_1017    conda-forge
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pillow                    6.2.1            py37h6b7be26_0    conda-forge
     pip                       19.3.1                   py37_0
     psutil                    5.6.3            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     pyarrow                   0.14.1           py37h8b68381_2    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     python                    3.7.3                h5b0a415_0    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  7.0                  h7b6447c_5
     requests                  2.22.0                   pypi_0    pypi
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.10.0                   py37_0    rapidsai
     setuptools                41.4.0                   py37_0
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.30.1               h7b6447c_0
     tblib                     1.4.0                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.6                   pypi_0    pypi
     wheel                     0.33.6                   py37_0
     xorg-fixesproto           5.0               h14c3975_1002    conda-forge
     xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
     xorg-libxi                1.7.10               h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-libxtst              1.2.3             h14c3975_1002    conda-forge
     xorg-recordproto          1.14.2            h14c3975_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7             h14c3975_1001    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

**Comment by SinsBre** [comment]
This _sometimes_ fixes the issue

$ ps -a | grep -i "blazin"

 3213 tty2     00:32:00 blazingsql-orch <defunct>
 3214 tty2     00:00:00 blazingsql-engi <defunct>
15504 tty2     00:00:00 blazingsql-engi <defunct>
15985 pts/2    00:00:00 blazingsql-engi

$ kill 15985

**Comment by felipeblazing** [comment]
I am guessing calcite is left dangling. We are working on fixing the cases that cause this issue. For now you could also do the following:
```netstat -tulpn | grep 8890```
Then kill the PID you see there

**Comment by SinsBre** [comment]
Update:

I can run a script and it works flawlessly. When I try to rerun the script it fails.
netstat -tulpn | grep 8890 returns blank.

If I wait for some time before I rerun the script it works.
This was not an issue in the last version of blazing.

Output:
`WARNING: blazingsql-orchestrator was not automativally started, its probably already running
Traceback (most recent call last):
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/blazingdb/protocol/__init__.py", line 59, in __init__
    connection.socket_.connect(connection.address())
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cs_dataprep.py", line 17, in <module>
    bc = BlazingContext()
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 173, in __init__
    internal_api.SetupOrchestratorConnection(orchestrator_host_ip, orchestrator_port)
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/pyblazing/api.py", line 904, in SetupOrchestratorConnection
    client.connect(orchestrator_host_ip, orchestrator_port)
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/pyblazing/api.py", line 353, in connect
    self._orchestrator_port, requestBuffer)
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/pyblazing/api.py", line 310, in _send_request
    client = blazingdb.protocol.Client(connection)
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/blazingdb/protocol/__init__.py", line 61, in __init__
    raise RuntimeError("Communication error: connection to " + str(connection.address()) + " was lost")
RuntimeError: Communication error: connection to ('localhost', 8889) was lost
Exception ignored in: <function BlazingContext.__del__ at 0x7f797ac62510>
Traceback (most recent call last):
  File "/media/REMOVED/Data/anaconda3/envs/blazing_test/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 212, in __del__
    if self.need_shutdown:
AttributeError: 'BlazingContext' object has no attribute 'need_shutdown'`

**Comment by felipeblazing** [comment]
Ok I think I know what is happening. The processes are not shutting down properly. So the BlazingContext goes out of scope then the services can't restart. We are looking into this. Is it possible to use something like a jupyter notebook to keep the context in scope?

**Comment by felipeblazing** [comment]
I am only suggesting this as a very temporary work aroudn we should have this resolved tomorrow.

**Comment by SinsBre** [comment]
I'll survive with jupyter until it's fixed. =)

**Comment by aucahuasi** [comment]
@williamBlazing made some fixes for this one, @SinsBre could you please try again? ;)

**Comment by aucahuasi** [comment]
Hi @SinsBre this issue was fixed with the latest improvements by @williamBlazing !

**Comment by SinsBre** [comment]
> Hi @SinsBre this issue was fixed with the latest improvements by @williamBlazing !

I'll test today, sorry for late response.
