### ISSUE TITLE
[DOC]slack join link invalid

### ISSUE THREAD

**Issue by senseb** [BlazingDB/pyBlazing#119]
## Report incorrect documentation
https://github.com/BlazingDB/pyBlazing/blob/develop/README.md

**Location of incorrect documentation**
Feel free to join our Slack chat room: [RAPIDS Slack Channel](https://join.slack.com/t/rapids-goai/shared_invite/enQtMjE0Njg5NDQ1MDQxLTViZWFiYTY5MDA4NWY3OWViODg0YWM1MGQ1NzgzNTQwOWI1YjE3NGFlOTVhYjQzYWQ4YjI4NzljYzhiOGZmMGM)

**Describe the problems or issues found in the documentation**
slack pages says: This invite link is no longer active.

**Steps taken to verify documentation is incorrect**
click

**Suggested fix for documentation**
post active slack link

**Comment by senseb** [comment]
can somebody update the slack channel?

**Comment by aucahuasi** [comment]
Hi @senseb thanks for reviewing our docs, could please try with this one https://app.slack.com/client/T5E06F3CN/C5E06F4DC

**Comment by roaramburu** [comment]
Updated the link in the edocs. Thank you.
