### ISSUE TITLE
[BUG] GCP Bucket - Can't pull from bucket which is private and requires a JSON Key

### ISSUE THREAD

**Issue by Djdraper12** [BlazingDB/pyBlazing#121]
**Describe the bug**
Cannot register the filesystem: Couldn't create gcs::ClientOptions for Project ID XXXXX
status=Could not automatically determine credentials. For more information, please see https://developers.google.com/identity/protocols/application-default-credentials

**Steps/Code to reproduce bug**
bc.gcs('dir_name',project_id='xxx,bucket_name='xxx',use_default_adc_json_file=False,adc_json_file='../home/david/Downloads/a3e4838767e8.json')

**Expected behavior**
Using JSON from service account credentials.

**Environment overview (please complete the following information)**
Docker Pull

**Comment by felipeblazing** [comment]
Can you try passing the full path instead of using a relative path for the location of the json file. I think that we still need to enable using relative paths there.

**Comment by aucahuasi** [comment]
Hi @Djdraper12 thanks, have you try to suggestion made  by @felipeblazing also how did you generate the json file, with gsutil command?

**Comment by Djdraper12** [comment]
Apologies - yes I did try but it's not working still.

**Comment by aucahuasi** [comment]
Hi @Djdraper12 How did you create the JSON file?

cc @jeanp413

**Comment by aucahuasi** [comment]
cc @mario21ic !

**Comment by Djdraper12** [comment]
I am creating it in the gcp console

**Comment by aucahuasi** [comment]
@Djdraper12 Thanks, could you please send us the link of Google Cloud documentation? So we can replicate the exact same steps? Another question, do you have this file in you home folder .config/gcloud/application_default_credentials.json ? If not, can you try again using the default authentication credentials? cc @mario21ic @jeanp413

**Comment by Djdraper12** [comment]
https://cloud.google.com/iam/docs/creating-managing-service-account-keys

**Comment by aucahuasi** [comment]
Hi @Djdraper12 thanks for reporting this, so the PR https://github.com/BlazingDB/blazingdb-io/pull/27 fixes the issue and this one will be available in our next release! Thanks @jeanp413 @mario21ic
