### ISSUE TITLE
In《Data Lake to AI — BlazingSQL + RAPIDS Initial Benchmark》，the E2E workflow Repo had gone？

### ISSUE THREAD

**Issue by halleyshx** [BlazingDB/pyBlazing#55]
The doc Url is `https://blog.blazingdb.com/data-lake-to-ai-blazingsql-rapids-initial-benchmark-aa753031ac8b`

> To see the E2E workflow, see our **Public Github Repo**.
> 
> You can see the full workload at the link above, but we want to go over a few code snippets to show you how you can expect to interact with BlazingSQL.

The Public Github Repo url is `https://github.com/BlazingDB/blazingsql-public-demos/blob/master/mortgage-xgboost/e2e.py` ,but it is 404.

**Comment by roaramburu** [comment]
Oh, you're right. Just made it public again. That was a mistake.

**Comment by roaramburu** [comment]
I also just realized that script will no longer run. 

It's from BlazingSQL & RAPIDS V 0.2 each respectively. We'll have to update, but we're focusing on other workloads/benchmarks right now, so those will probably come out before the re-work of this one.
