### ISSUE TITLE
Python does not start services automatically

### ISSUE THREAD

**Issue by editaxz** [BlazingDB/pyBlazing#61]
Hello, to execute a simple demo. I can see the query result is correct but in the end there is a weird message:

Demo:
----------
from blazingsql import BlazingContext
bc = BlazingContext()
import time
nation = bc.create_table('nation', '/tmp/nation_0_0.parquet')
sql = "select n_nationkey, n_comment from nation"
result_gdf = bc.sql(sql).get()
print(result_gdf)

Output:
----------

(blazingsql) root@8d16c30f8ae3:~# python hola.py 
connection established
columns =     n_nationkey                                          n_comment
0             0   haggle. carefully final deposits detect slyly...
1             1  al foxes promise slyly according to the regula...
2             2  y alongside of the pending deposits. carefully...
3             3  eas hang ironic, silent packages. slyly regula...
4             4  y above the carefully unusual theodolites. fin...
5             5                    ven packages wake quickly. regu
6             6             refully final requests. regular, ironi
7             7  l platelets. regular accounts x-ray: unusual, ...
8             8  ss excuses cajole slyly across the packages. d...
9             9   slyly express asymptotes. regular deposits ha...
10           10  efully alongside of the slyly final dependenci...
11           11  nic deposits boost atop the quickly final requ...
12           12               ously. final, express gifts cajole a
13           13  ic deposits are blithely about the carefully r...
14           14   pending excuses haggle furiously deposits. pe...
15           15  rns. blithely bold courts among the closely re...
16           16      s. ironic, unusual asymptotes wake blithely r
17           17  platelets. blithely pending dependencies use f...
18           18  c dependencies. furiously express notornis sle...
19           19  ular asymptotes are about the furious multipli...
20           20  ts. silent requests haggle. closely express pa...
21           21     hely enticingly express accounts. even, final 
22           22   requests against the platelets use never acco...
23           23  eans boost carefully special requests. account...
24           24  y final packages. slow foxes cajole quickly. q...
                    resultToken = 14785780709824492479
                    interpreter_path = 127.0.0.1
                    interpreter_port = 8891
                    handle = [<numba.cuda.cudadrv.driver.IpcHandle object at 0x7ff86d2819b0>]
                    client = <pyblazing.api.PyConnector object at 0x7ff86d2daef0>
                    calciteTime = 301
                    ralTime = 310
                    totalTime = 851
                    error_message = 
Exception ignored in: <function ResultSetHandle.__del__ at 0x7ff86d2e42f0>
Traceback (most recent call last):
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 310, in __del__
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 229, in free_result
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 47, in _send_request
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/blazingdb/protocol/__init__.py", line 71, in send
TypeError: can only concatenate str (not "tuple") to str
Exception ignored in: <function PyConnector.__del__ at 0x7ff86d2d6c80>
Traceback (most recent call last):
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 64, in __del__
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 108, in close_connection
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/pyblazing/api.py", line 46, in _send_request
  File "/miniconda3/envs/blazingsql/lib/python3.7/site-packages/blazingdb/protocol/__init__.py", line 61, in __init__
TypeError: can only concatenate str (not "tuple") to str
Colla

**Comment by GarrisonD** [comment]
Looks like I ran into the same issue:

```
Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str
Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str
columns = None
                    resultToken = 14399528693250841573
                    interpreter_path = 127.0.0.1
                    interpreter_port = 8891
                    handle = None
                    client = <pyblazing.api.PyConnector object at 0x7fcf338f9748>
                    calciteTime = 21
                    ralTime = 0
                    totalTime = 0
                    error_message = Unexpected error on _run_query_get_results, can only concatenate str (not "tuple") to str
```

**Comment by aucahuasi** [comment]
Same as https://github.com/BlazingDB/pyBlazing/issues/117 fixed!
