### ISSUE TITLE
No such file or directory: 'blazingsql-orchestrator': 'blazingsql-orchestrator'

### ISSUE THREAD

**Issue by ivenzor** [BlazingDB/pyBlazing#70]
I'm testing the conda installation procedure released 3 days ago.
_(rapids) sh-4.2$ conda list | grep blazing
blazingdb-toolchain       0.4.0            py37hf484d3e_0    blazingsql
blazingsql-calcite        0.4.0                    py37_0    blazingsql
blazingsql-communication  0.4.0                   py37_80    blazingsql
blazingsql-io             0.4.0                   py37_31    blazingsql
blazingsql-orchestrator   0.4.0                   py37_19    blazingsql
blazingsql-protocol       0.4.0                   py37_25    blazingsql
blazingsql-python         0.4.0           cuda10.0_py37_14    blazingsql/label/cuda10.0
blazingsql-ral            0.4.0           cuda10.0_py37_5    blazingsql/label/cuda10.0_

However when I try to _bc = BlazingContext()_  I got the following:
AttributeError: 'BlazingContext' object has no attribute 'processes'
FileNotFoundError: [Errno 2] No such file or directory: 'blazingsql-orchestrator': 'blazingsql-orchestrator'

Perhaps there is something else I need to do before I call bc = BlazingContext() that I'm not aware of?

**Comment by bordie** [comment]
FWIW - I am trying the conda install and do not have this issue. I show the same versions of all blazing* as above.

**Comment by ivenzor** [comment]
Thanks for the reply. 
These are my steps:

_source /home/ec2-user/anaconda3/etc/profile.d/conda.sh
sudo mkdir /blazingsql
sudo chown ec2-user /blazingsql
conda create --name rapids_blazing python=3.7
conda activate rapids_blazing

conda install -c rapidsai -c nvidia -c numba -c conda-forge -c anaconda -c rapidsai/label/xgboost -c blazingsql/label/cuda10.0 -c blazingsql blazingsql-calcite blazingsql-orchestrator blazingsql-ral blazingsql-python "rapidsai/label/xgboost::xgboost=>0.9" cudf=0.9 cuml=0.9 cugraph=0.9 dask-cudf=0.9 python=3.7 ipykernel boto3 "PyYAML>=3.10,<4.3" "urllib3<1.25,>=1.21" "idna<2.8,>=2.5" boto s3fs dask anaconda::cudatoolkit=10.0

pip install flatbuffers sagemaker
ipython kernel install --user --name=rapids_blazing_

After that I go to Jupyter Lab and open the notebook. I import the packages but got the error when I try to bc = BlazingContext()

**Comment by felipeblazing** [comment]
Is the notebook running inside of the conda environment rapids_blazing?

**Comment by ivenzor** [comment]
I think I have found the issue. It was a sily thing. I will test more and will let you know.

**Comment by aucahuasi** [comment]
@ivenzor thanks for reporting this, I think the issue is that you need to run BlazingSQL and Jupyter with the same conda env.

**Comment by ivenzor** [comment]
The fix was just to specify the kernel to be conda_rapids_blazing instead of rapids_blazing.
