### ISSUE TITLE
[BUG] Distributed Query client = Client('127.0.0.1:8786')  error

### ISSUE THREAD

**Issue by ivenzor** [BlazingDB/pyBlazing#83]
In blazingsql (0.4.4) I want to execute a distributed sql on several GPUs. According to the documentation, the first steps are:
```
from blazingsql import BlazingContext
import cudf
import dask_cudf
import dask
from dask.distributed import Client
client = Client('127.0.0.1:8786')
```

However, in client = Client('127.0.0.1:8786') I got the following error:
`OSError: Timed out trying to connect to 'tcp://127.0.0.1:8786' after 10 s: in <distributed.comm.tcp.TCPConnector object at 0x7f97eb566e80>: ConnectionRefusedError: [Errno 111] Connection refused
`
I would like to know if there is something else I need to do or if the error is because of something not working in my environment.

**Comment by felipeblazing** [comment]
You need to have a dask cluster already running. If you dont not have one just do
client = Client() and that will launch one for you.

**Comment by ivenzor** [comment]
My bad, you are correct.

Question, when #82 is solved will I be able to specify the dask_cudf dataframe in the create table and then all the selects will be automatically split in all available gpus?

**Comment by aucahuasi** [comment]
@ivenzor I don't have at hand the implementation details of the create table for dask_cudf, but as far I can tell, yes when #82 is ready you can create a table based on dask_cudf and by using dask together with our distributed engines then the data will be distributed among your available GPUs. Tomorrow I will ask @gcca or @felipeblazing confirm all of this or give more details! Thanks once again +1

**Comment by felipeblazing** [comment]
Yes that is the case. There  might be some issues if dask has multiple partitions per client but we will work on fixing that in the next few days.
