### ISSUE TITLE
[QST] Is LIKE supported?

### ISSUE THREAD

**Issue by sandyandi** [BlazingDB/pyBlazing#84]
**What is your question?**
Hello. I'm trying to filter my data set using the LIKE filter but I always get the same result regardless of the filter value I use. So I'm wondering if LIKE is actually supported.

**Comment by aucahuasi** [comment]
Thanks @sandyandi 
We are close to make a new release in which we will have LIKE support (we are doing some final testing phases right now) Until that, is it possible you can share with us your queries or python script/snippets?
We will notify as soon we have the new release!

**Comment by sandyandi** [comment]
Thanks @aucahuasi for the speedy response and we're very excited to try out your next release!

We are in the early stage of evaluating BlazingSQL for data transformation. At the moment, we just need a way to filter our data to find records with fields containing substrings among other things. eg: `WHERE product_description LIKE "%sneakers%" OR product_description LIKE "%nike%" OR price > 10`.

**Comment by felipeblazing** [comment]
Like is now implemented. You should be able to use it

**Comment by sandyandi** [comment]
Thanks @felipeblazing! By the way, I'm using the BlazingSQL docker image and it seems like it's not yet updated. Looking forward to the latest docker image. Cheers!

**Comment by sandyandi** [comment]
@felipeblazing may I know which version is `LIKE` implemented? It seems the latest version that was released (v0.4.4) still doesn't have it. Also, if the `LIKE` is not yet supported, is there any available function for substring matching at the moment?

**Comment by felipeblazing** [comment]
It does have like. Can I see how you were using it?

**Comment by sandyandi** [comment]
I'm using it seomthing like the following:
```python
from blazingsql import BlazingContext

bc = BlazingContext()

col_names = ['col_1','col_2','col_3']

bc.create_table('table_name', '/path/to/file.csv', names=col_names)

result = bc.sql("SELECT col_1, col_2 FROM table_name WHERE col_2 LIKE '%some-substring%' LIMIT 5").get()

print(result.columns)
```
And it keeps giving the same result even when I change the `some-substring` to something else.
