### ISSUE TITLE
[DOC] mkdir /blazingsql

### ISSUE THREAD

**Issue by gumdropsteve** [BlazingDB/pyBlazing#93]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/BlazingDB/pyBlazing#install-using-conda

**Describe the problems or issues found in the documentation**
When installing with Conda, changing the first two commands from this:
```
mkdir /blazingsql # Make a blazingsql directory in root folder for Apache Calcite schema management. This will requirement will be removed soon.

chown <user_name> /blazingsql
```
to this:
```
sudo mkdir /blazingsql
sudo chmod 777 /blazingsql
```
resolved [my comment](https://github.com/BlazingDB/pyBlazing/issues/72#issuecomment-543453623) in issue #72 

**Steps taken to verify documentation is incorrect**
Installed in multiple Conda environments, with both `blazingsql` and `blazingsql-nightly`

**Suggested fix for documentation**
Add `sudo ` before `mkdir /blazingsql` in the instructions to make the first line read:
```
sudo mkdir /blazingsql
```
Not sure changing the 2nd line is needed, or that `777` instead of `<user_name>` is a preferable option

**Comment by felipeblazing** [comment]
We have made that directory no longer necessary. This has been fixed with PR [PR-94](https://github.com/BlazingDB/pyBlazing/pull/94). A new build should go out by the end of the day that will solve this issue for conda installs
