### ISSUE TITLE
[BUG] Reading from csv/cudf with `blazing` and `dask_client`  fails

### ISSUE THREAD

**Issue by VibhuJawa** [BlazingDB/pyBlazing#95]
**Describe the bug**

Reading from csv with `blazing` and `dask_client`  seems to be failing.  Below works if i dont supply the dask client to the `blazing context` .

**Steps/Code to reproduce bug**

```python
import dask_cudf 

from blazingsql import BlazingContext
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
from distributed import wait
from dask import delayed
import os
import cudf
import pandas as pd
```

```python
### start workers
cluster = LocalCUDACluster()
client = Client(cluster)

bc = BlazingContext(dask_client=client)
bc
```
##### Script that bugs
```python
pd.DataFrame({'1':[0,1,2]}).to_csv('test.csv',index=False)
result = bc.create_table('test', os.getcwd()+'/'+'test.csv')
table_result = bc.sql('SELECT * FROM test').get()
table_df = table_result.columns
table_df
```

Python Output:
```
Index(['1'], dtype='object')
```
Dask Worker Trace
```
distributed.worker - WARNING -  Compute Failed
Function:  convert_to_dask
args:      ([<class 'blazingdb.protocol.transport.responses'>], <pyblazing.api.PyConnector object at 0x7f574a735048>)
kwargs:    {}
Exception: CudaAPIError(217, 'Call to call_cuIpcOpenMemHandle results in UNKNOWN_CUDA_ERROR')
```

**Expected behavior**
I would expect the behavior to be same independent of providing dask-client. 

**Environment overview (please complete the following information)**
- Environment location: Docker
- Blazing Build: Source
- Cudf Build - Docker dev container 

**Follow up question:**

Are there examples workflows of using `dask-cudf` with `blazing` you can share . It will be super helpful .

**Comment by aucahuasi** [comment]
Hi @VibhuJawa thanks, @felipeblazing or @gcca could you please look this issue?

**Comment by aucahuasi** [comment]
Hi @VibhuJawa just to let you know we are already working on dask issues, we hope to get some good news about this one soon. Thanks!

**Comment by aucahuasi** [comment]
Hi @VibhuJawa status update we're still working on this one, we'll let you know as soon we have good news!

**Comment by aucahuasi** [comment]
Hi @VibhuJawa these PRs solve this issue

https://github.com/BlazingDB/pyBlazing/pull/138
https://github.com/BlazingDB/blazingdb-ral/pull/245

You can try our nightly packages:

`conda install -c blazingsql-nightly/label/cuda10.0 -c blazingsql-nightly -c rapidsai-nightly -c conda-forge -c defaults python=3.7 blazingsql
`

Thanks!
